email-templates/common-en_US/footer.ejs, email-templates/common-en_US/header.ejs, email-templates/ticket-application-approved-en_US/html.ejs, email-templates/ticket-application-approved-to-dojo-en_US/html.ejs, email-templates/ticket-application-approved-to-dojo-en_US/text.ejs, email-templates/ticket-application-cancelled-en_US/html.ejs, email-templates/ticket-application-cancelled-en_US/text.ejs, email-templates/ticket-application-received-en_US/html.ejs, email-templates/ticket-application-received-en_US/text.ejs, email-templates/ticket-application-received-to-dojo-en_US/html.ejs, email-templates/ticket-application-received-to-dojo-en_US/text.ejs, package.json, strings/en_US/messages.po
[#882](https://github.com/CoderDojo/community-platform/issues/882)
=> Strings and templates for event email notifications

email-templates/dojo-submitted-en_US/html.ejs, email-templates/dojo-submitted-en_US/text.ejs, strings/en_US/messages.po
=> Register a Dojo & Find Dojo

strings/en_US/messages.po
Ref : https://github.com/CoderDojo/cp-zen-frontend/pull/63
=> Allow-cancel-booking strings

strings/en_US/messages.po
Parent PR : https://github.com/CoderDojo/cp-zen-frontend/pull/97
=> Add string for next event display on dojo listing

strings/en_US/messages.po
Related PR :https://github.com/CoderDojo/cp-zen-frontend/pull/98/files
=> Add string for Recent Events on dojo listing page

strings/en_US/messages.po
=> Copy changes for booking flow

strings/en_US/messages.po
Which is an alternative string for users without dojo or leads or join requests
=> Add new dashboard string

test/validStrings/user-request-to-join.spec.js
However, I'm expecting it to fail on the old templates...
=> Fix tests, by adding the new string to the email template test

strings/en_US/messages.po
used on manage-users page for pending requests
=> Add string for conflict on join-request

package.json, strings/en_US/messages.po
Also add a couple of other strings that were giving errors locally.
=> Add new strings from new event form

strings/en_US/messages.po
This changes the sentence structure to make it easier to translate.
=> Amend strings used on events page

strings/en_US/messages.po
Adds string needed for validation error.
=> Add event date required string

strings/en_US/messages.po
Add messages for raspberry linked account login.
Strings used in PR https://github.com/CoderDojo/cp-zen-frontend/pull/282
=> Add messages for raspberry linked account login.

changelog.md, strings/en_US/messages.po
Addind the required strings to cp-translations to be pulled into relevant apps.
=> Add strings for covid banner

changelog.md
Fixed Dutch email translation templates in Crowdin.
=> Update changelog.md - Fix Dutch translations

strings/en_US/messages.po
Closes #123 
I've not removed the "old" copy as we probably want to make sure everything using those strings have been updated before doing so.
=> Added new copy strings

.circleci/config.yml, README.md, changelog.md
Need to add new languages from Crowdin to the circleci config.
=> Add 'ar' language to Circle CI build

strings/en_US/messages.po
=> Updates banner text

strings/en_US/messages.po
As per new copy requirements in
https://docs.google.com/document/d/1efxWcuq-k_yEUCTieYO3eMjJnrvyOkBT7TTYCum5lwM/edit
=> Update strings for new safeguarding copy

strings/en_US/messages.po
Relates to: https://github.com/CoderDojo/cp-zen-platform/issues/1444
=> Update translation strings for Keeping Your Dojo Safe

strings/en_US/messages.po
Relates to https://github.com/CoderDojo/cp-zen-platform/issues/1443
=> 1443: Add translation string in for SAD form

email-templates/dojo-submitted-en_US/html.ejs, email-templates/dojo-submitted-en_US/text.ejs, strings/en_US/messages.po
Sets expectations around timescales
Fixes https://raspberrypi.monday.com/boards/1236004929/pulses/1412720797
=> Update templates with new verification timescales

strings/en_US/messages.po
=> Update and add messages for new applications
